tables = [
    [('model_name',), ['roberta-base']],
    [('dataset',), ["pg19_retriever_data/prefix_256_suffix_gold_10_to_98_self_negative_no_sent_boundary"]],
    [('batch_size',), [1]],
    [('accumulation',), [1]],
    [('num_epochs',), [6]],
    [('beam_size',), [1]],
    [('eval_batch_size',), [1]],
    [('learning_rate',), ["1e-5"]],
    [('gpu',), ["rtx8000-long"]],
    [('ngpus',), ["1"]],
    [('master_port',), ["4577"]],
    [('prefix_input_type',), ["original"]],
    [('global_dense_feature_list',), ["none"]],
    [('stop_token',), ["eos"]],
    [('save_steps',), [500]],
    [('save_total_limit',), [-1]],
    [('specific_style_train',), [-1]],
    [('optimizer',), ["adam"]],
    [('negative_examples',), ["negatives_suffix"]],
    [('prefix_truncate_dir',), ["left"]],
    [('eval_frequency_min',), ["30"]],
]

lit_analysis = [
    [('model_name',), ['roberta-base']],
    [('dataset',), ["relic_preprocessed/left_0_right_1_neg_100"]],
    [('batch_size',), [1]],
    [('accumulation',), [1]],
    [('num_epochs',), [10]],
    [('beam_size',), [1]],
    [('eval_batch_size',), [1]],
    [('learning_rate',), ["1e-5"]],
    [('gpu',), ["rtx8000-short"]],
    [('ngpus',), ["1"]],
    [('master_port',), ["4789"]],
    [('prefix_input_type',), ["original"]],
    [('global_dense_feature_list',), ["none"]],
    [('stop_token',), ["eos"]],
    [('save_steps',), [250]],
    [('save_total_limit',), [-1]],
    [('specific_style_train',), [-1]],
    [('optimizer',), ["adam"]],
    [('negative_examples',), ["suffix"]],
    [('prefix_truncate_dir',), ["right"]],
    [('eval_frequency_min',), ["10"]],
]
