lit_analysis = [
    [('model_name',), ['roberta-base']],
    [('dataset',), ["relic_preprocessed/left_4_right_4_neg_100"]],
    [('batch_size',), [1]],
    [('accumulation',), [1]],
    [('num_epochs',), [10]],
    [('beam_size',), [1]],
    [('eval_batch_size',), [1]],
    [('learning_rate',), ["1e-5"]],
    [('gpu',), ["rtx8000-short"]],
    [('ngpus',), ["1"]],
    [('master_port',), ["4789"]],
    [('stop_token',), ["eos"]],
    [('save_steps',), [250]],
    [('save_total_limit',), [-1]],
    [('optimizer',), ["adam"]],
    [('negative_examples',), ["suffix"]],
    [('prefix_truncate_dir',), ["right"]],
    [('eval_frequency_min',), ["10"]],
]
